### ISSUE TITLE
Quando há código idêntico, ou similar, em componentes. Em alguns casos, devemos extrair para um terceiro ao invés de apenas extender do já existente.

### ISSUE THREAD

**Issue by rodrigomaia** [fernandodev/guidenel#3]
Ex: Temos dois componentes, A e B, com códigos similares. B nunca deve extender de A, nem vice versa, exceto se B realmente é um A. Por exemplo, se A é um combo de sistemas e B também, só que em outro contexto com suas peculiaridades, ele pode ser extendido sim.
Já para reaproveitar código apenas para remover a duplicação, devemos criar um C com o código similar e tanto A quanto B devem extender C.

**Comment by aquinofb** [comment]
+1

**Comment by fernandodev** [comment]
Eu sugiro não herdar, mas compor. Assim diminui o acoplamento e aumenta a reutilização dos modelos. Ou seja, os códigos similares entre A e B devem ser extraídos para um modelo/helper o que for e assim, ser reutilizado dentro das classes A e B e futuras 

http://www.devmedia.com.br/heranca-versus-composicao-qual-utilizar/26145

**Comment by rodrigomaia** [comment]
se A é um combo de sistemas e B também, só que em outro contexto com suas peculiaridades, ele pode ser extendido sim.
Já para reaproveitar código apenas para remover a duplicação, devemos criar um C com o código similar e tanto A quanto B devem extender C.
