### ISSUE TITLE
Indentação de métodos aninhados com quebra de linha

### ISSUE THREAD

**Issue by aquinofb** [fernandodev/guidenel#4]
Exemplo do Leitor10:
joins(:admin_grupos).
where(organization_id: current_user.last_organization_logged, admin_grupos: { user_id: current_user.id}).
order(created_at: :desc)

**Comment by fernandodev** [comment]
Acho que fica melhor assim:
* com o ponto antes do nome do método e não na linha anterior
* com parâmetros longos quebrados em linhas mais semânticas

```ruby
joins(:admin_grupos)
  .where
    (
      organization_id: current_user.last_organization_logged, 
      admin_grupos: { user_id: current_user.id }
    )
  .order(created_at: :desc)
```

**Comment by fernandodev** [comment]
Ver: https://github.com/bbatsov/ruby-style-guide

**Comment by rodrigomaia** [comment]
Ponto no inicio da linha
Siga o padrão:
```ruby
joins(:admin_grupos)
  .where
    (
      organization_id: current_user.last_organization_logged, 
      admin_grupos: { user_id: current_user.id }
    )
  .order(created_at: :desc)
```
